version: "3.1"

services:

  app:
    build: .
    restart: always
    environment:
      SQL_CREDENTIALS: root:password
      SQL_DSN: mysql:3306
      QUEUE_URL: /dev/null
      APP_PORT: 8080
      LOG_LEVEL: info
    depends_on:
      - mysql
    ports:
    - 8080:8080

  mysql:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_DATABASE: dev
      MYSQL_ROOT_PASSWORD: password
    ports:
    - 3306:3306