version: "3.1"

services:

  app:
    build: .
    restart: always
    environment:
      SQL_CREDENTIALS: password
      FACTSET_DSN: root:password@mysql/test
      APP_PORT: 8080
      LOG_LEVEL: info
    ports:
    - 8080:8080

  mysql:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    ports:
    - 3306:3306